### ISSUE TITLE
Missing VI "COPY.vi"

### ISSUE THREAD

**Issue by 3ncor** [levylabpitt/pq-labview#2]
Hi, I'm tring to open up tne Instrument-Framework and found that it requires `COPY.vi` from the PostSQL labview package, however this VI is not included in this repo or the upstream. I don't know if this is the right place to ask but I think maybe you forget to commit the file when forking the upstream repo? If so, can you add the missing file? Thanks.

**Comment by ciozi137** [comment]
@3ncor sorry I just saw your message. Instrument Framework does not use COPY.vi, but it is part of a dependency of a dependency... But you're in luck because the upstream version was just released yesterday: https://www.vipm.io/package/jdp_science_postgresql/

**Comment by 3ncor** [comment]
The upstream update solved the dependency issue perfectly 😃 , thank you.
